name: q4c12-d2cpack
version: "0"
synopsis: "Opinionated wrapper around dhall-to-cabal"
description: |
  A very thin, opinionated wrapper around dhall-to-cabal, providing a hpack-like interface: it reads from a well-known file in the current working directory (@package.dhall@) and writes to a @.cabal@ file whose name is determined by the package's name.
homepage: https://github.com/quasicomputational/mega/tree/master/packages/d2cpack
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
extra-source-files:
  - CHANGELOG.markdown
defaults:
  local: ../../hpack/defaults.rolling.yaml

_common-dependencies:
    # Define version ranges once and only once across components.
  - &d-Cabal
    "Cabal >= 2.2 && < 2.3"
  - &d-dhall-to-cabal
    "dhall-to-cabal >= 1.2.0.0 && < 1.3"
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.1"
  - &d-text
    "text >= 1.2.2.2 && < 1.3"

executables:
  d2cpack:
    source-dirs:
      - driver/
    main: Main.hs
    # Suppress Paths_*
    other-modules: []
    dependencies:
      - *d-Cabal
      - *d-dhall-to-cabal
      - *d-q4c12-prelude
      - *d-text
