sudo: false
language: generic

#TODO: hlint, GHC HEAD, cabal check, building a sdist then testing the sdist, checking the sdist isn't missing files, packunused, maybe packdeps?
matrix:
  include:
    - env: CMD=stack OPTIONS=--ghc-options=-Werror
    - env: CMD=stack OPTIONS="--resolver nightly"
    - env: CMD=cabal-new-test OPTIONS="--project-file=cabal.ghc-8.2.project"
      addons: {apt: {packages: [ghc-8.2.2,cabal-install-2.0], sources: [hvr-ghc]}}
    - env: CMD=cabal-new-test OPTIONS="--project-file=cabal.ghc-8.0.project"
      addons: {apt: {packages: [ghc-8.0.2,cabal-install-2.0], sources: [hvr-ghc]}}
    - env: CMD=cabal-new-test OPTIONS="--project-file=cabal.ghc-8.4.project --allow-newer" GHCHEAD=true
      addons: {apt: {packages: [ghc-8.4.1,cabal-install-head], sources: [hvr-ghc]}}
      #TODO: regularise once GHC 8.4's officially out

before_install:
  - mkdir -p "$HOME/.local/bin"
  - PATH=$HOME/.local/bin:/opt/ghc/bin:$PATH
  - export HPACKVER=0.27.0
  - curl -sL https://github.com/sol/hpack/releases/download/"$HPACKVER"/hpack_linux.gz | gunzip > ~/.local/bin/hpack
  - chmod +x ~/.local/bin/hpack
  #Note order: have to generate .cabal files before new-update! See https://github.com/haskell/cabal/issues/5096, though we have to do this at *some* point and it might as well be now.
  - find packages/ -path 'packages/*/package.yaml' -exec "$HOME/.local/bin/hpack" '{}' ';'
  #TODO: remove the condition once we can use cabal-install 2.2 and hence new-update in all configurations
  - |
    case "$CMD" in
    stack)
      curl -sL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
      stack setup
      ;;
    cabal-new-test)
      if ${GHCHEAD-false} ; then cabal new-update $OPTIONS; else cabal update; fi
      ;;
    esac

install:
  - |
    case "$CMD" in
    stack)
      stack --no-terminal test $OPTIONS --only-dependencies --fast
      ;;
    cabal-new-test)
      cabal new-build all --enable-tests --only-dependencies $OPTIONS
      ;;
    esac

script:
  - |
    case "$CMD" in
    stack)
      stack --no-terminal test $OPTIONS --haddock --no-haddock-deps --fast
      ;;
    cabal-new-test)
      cabal new-build all --enable-tests $OPTIONS
      cabal new-test all --enable-tests $OPTIONS
      ;;
    esac

notifications:
  email: false

cache:
  directories:
    - $HOME/.cabal/store
    - $HOME/.cabal/bin
    - $HOME/.stack/bin
    - $HOME/.stack/precompiled
    - $HOME/.stack/programs
    - $HOME/.stack/setup-exe-cache
    - $HOME/.stack/snapshots
