sudo: false
language: generic

#Configured for bors-ng
branches:
  only:
    - staging
    - trying
    #Let Travis trigger on tag pushes matching this pattern, so that the deploy stuff works
    - "/^release\\/"

#TODO: hlint, cabal check, building a sdist then testing the sdist, checking the sdist isn't missing files, packunused, maybe packdeps?
matrix:
  fast_finish: true
  include:
    - env: CMD=stack-werror RELEASE=true
    - env: CMD=stack-nightly
    - env: CMD=cabal-new-build GHCSERIES=8.0
      addons: {apt: {packages: [ghc-8.0.2,cabal-install-2.2], sources: [hvr-ghc]}}
    - env: CMD=cabal-new-build GHCSERIES=8.2
      addons: {apt: {packages: [ghc-8.2.2,cabal-install-2.2], sources: [hvr-ghc]}}
    - env: CMD=cabal-new-build GHCSERIES=8.4
      addons: {apt: {packages: [ghc-8.4.3,cabal-install-2.2], sources: [hvr-ghc]}}
    #TODO: regularlise once cabal-install 2.4 is out, and move out of allow-failures
    - env: CMD=cabal-new-build GHCSERIES=8.6
      addons: {apt: {packages: [ghc-8.6.1,cabal-install-head], sources: [hvr-ghc]}} 
    - env: CMD=cabal-new-build GHCSERIES=head
      addons: {apt: {packages: [ghc-head,cabal-install-head], sources: [hvr-ghc]}}
  allow_failures:
    #TODO: https://github.com/fpco/stackage/issues/3365; however, we possibly don't want to be beholden to nightly's whims anyway, so maybe this should be an allowed failure.
    - env: CMD=stack-nightly
    - env: CMD=cabal-new-build GHCSERIES=8.6
    - env: CMD=cabal-new-build GHCSERIES=head

before_install:
  - mkdir -p "$HOME/.local/bin"
  - export PATH=$HOME/.local/bin:/opt/ghc/bin:$PATH
  - export HPACKVER=0.27.0
  - curl -sL https://github.com/sol/hpack/releases/download/"$HPACKVER"/hpack_linux.gz | gunzip > ~/.local/bin/hpack
  - chmod +x ~/.local/bin/hpack
  #Note order: have to generate .cabal files before new-update! See https://github.com/haskell/cabal/issues/5096, though we have to do this at *some* point and it might as well be now.
  - find packages/ -path 'packages/*/package.yaml' -exec "$HOME/.local/bin/hpack" '{}' ';'
  - ./travis/before_install."$CMD".sh

install:
  - ./travis/install."$CMD".sh

script:
  - ./travis/script."$CMD".sh

before_deploy:
  - ./travis/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "EaKcfoWeuoZFXNE1JM9Cgq/T5e6by/udjWo+CDEuNSk0PQ1aLatotJecFGM3Rq2JqNE1VWLIMDukj9zpNw1QtAudalsySBulYK1Jz9G8AAXuKU2E1iQKdaPnivPCpRxnxMMDlscJObUc3W+oyZrdjO8mtpzVx6Y8sZl4oZRYhep03yV0B6H+pJEfKN0ixy2E/4ijx5N53+n7j8gzF2kF2BRqjoqoY2R2jIMDM0gzKrP8/Wuwz5/BPC4zUB4eRJym5mRE9ndCuEiwNYMWcdJ1nwVxYzfNu3KSJ55Fs8kp+AHQdvB5CJwQr+JWXrElNxWtOfJW7FEQF0DclxoDv/dWABsoxsm3Fk81kywaxBKoE9jgmVZSm6f+k2JRHMgZNgEvZLFg6u0KCeT/DczCO9wV3mXbydi1VqEiS1X5tkzGl53GQS2rfSAVAM61Iml/oK3EmD5Bfiv9cyLAItQa58KzhJdiTRGOlPEBDPrkeniCl/1mv2JDGfCEXAZWvjP0wCxLd6osnsZRMbir0uBizuCRsG70vn4LlwT12umdDvOurQzwqIeCl4hGZHM5PYEr2bAMiWXUltt+L9cB+LWLg6tnggmSZOt94tEyLT5Wb5J2xYZxUp5JmfmOW0nT9kanAUTR6gza7qfIntMbklECPhqnH5V4hvV3tgE6JT2tKahMP6k="
  file-glob: true
  file: "bin/*"
  skip-cleanup: true
  on:
    repo: quasicomputational/mega
    tags: true
    condition: "$RELEASE = true"

notifications:
  email: false

cache:
  directories:
    - $HOME/.cabal/store
    - $HOME/.cabal/bin
    - $HOME/.stack/bin
    - $HOME/.stack/precompiled
    - $HOME/.stack/programs
    - $HOME/.stack/setup-exe-cache
    - $HOME/.stack/snapshots
