sudo: false
language: haskell

#TODO: hlint, GHC HEAD, cabal check, building a sdist then testing the sdist, checking the sdist isn't missing files, packunused, maybe packdeps?
matrix:
  include:
    - env: CMD=stack OPTIONS=--ghc-options=-Werror
    - env: CMD=stack OPTIONS="--resolver nightly"
    - env: CMD=cabal-new-test OPTIONS="--project-file=cabal.ghc-8.2.project"
      ghc: "8.2.2"
      cabal: "2.0"
    - env: CMD=cabal-new-test OPTIONS="--project-file=cabal.ghc-8.0.project"
      ghc: "8.0"
      cabal: "2.0"

before_install:
  - mkdir -p "$HOME/.local/bin"
  - PATH=$HOME/.local/bin:$PATH
  - curl -sL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
  - stack setup
  - TMPDIR=$(mktemp -d)
  - pushd $TMPDIR
  - stack --no-terminal install hpack-0.21.2
  - popd

install:
  - find packages/ -path 'packages/*/package.yaml' -exec "$HOME/.local/bin/hpack" '{}' ';'
  - case "$CMD" in
    stack)
      stack --no-terminal test $OPTIONS --only-dependencies --fast
      ;;
    cabal-new-test)
      cabal new-build all --enable-tests --only-dependencies $OPTIONS
      ;;
    esac

script:
  - case "$CMD" in
    stack)
      stack --no-terminal test $OPTIONS --haddock --no-haddock-deps --fast
      ;;
    cabal-new-test)
      cabal new-test all --enable-tests $OPTIONS
      ;;
    esac

notifications:
  email: false

cache:
  directories:
    - $HOME/.cabal/store
    - $HOME/.cabal/bin
    - $HOME/.stack/bin
    - $HOME/.stack/precompiled
    - $HOME/.stack/programs
    - $HOME/.stack/setup-exe-cache
    - $HOME/.stack/snapshots
