resolver: nightly-2019-04-26
packages:
  - location: ./packages/xml-core
  - location: ./packages/xml-desc
  - location: ./packages/xhtml2html
  - location: ./packages/twofinger
  - location: ./packages/prelude
  - location: ./packages/romnum
  - location: ./packages/foldable-utils
  - location: ./packages/hlist
  - location: ./packages/position
  - location: ./packages/meta
  - location: ./packages/project-file
  - location: ./packages/defrost
  - location: ./packages/aeson-cabal
