resolver: nightly-2018-02-28
packages:
  - location: ./packages/xml
  - location: ./packages/mappend
  - location: ./packages/twofinger
  - location: ./packages/prelude
  - location: ./packages/romnum
  - location: ./packages/foldable-utils
  - location: ./packages/hlist
  - location: ./packages/position
extra-deps:
  #TODO: remove base-prelude extra-dep once it makes it back into Stackage. https://github.com/fpco/stackage/issues/3202 is part of it.
  - base-noprelude-4.10.1.0@rev:0
  #TODO: https://github.com/fpco/stackage/issues/3312
  - transformers-compat-0.6.0.5@rev:0
