resolver: nightly-2018-07-11
packages:
  - location: ./packages/xml-core
  - location: ./packages/xml-desc
  - location: ./packages/xhtml2html
  - location: ./packages/mappend
  - location: ./packages/twofinger
  - location: ./packages/prelude
  - location: ./packages/romnum
  - location: ./packages/foldable-utils
  - location: ./packages/hlist
  - location: ./packages/position
  - location: ./packages/gen-travis
