resolver: nightly-2019-06-04
packages:
  - ./packages/xml-core
  - ./packages/xml-desc
  - ./packages/xhtml2html
  - ./packages/twofinger
  - ./packages/prelude
  - ./packages/romnum
  - ./packages/foldable-utils
  - ./packages/hlist
  - ./packages/position
  - ./packages/meta
  - ./packages/project-file
  - ./packages/defrost
  - ./packages/aeson-cabal
  - ./packages/dhondt
