resolver: nightly-2018-01-27
packages:
  - location: ./packages/xml
  - location: ./packages/mappend
  - location: ./packages/twofinger
  - location: ./packages/prelude
  - location: ./packages/romnum
  - location: ./packages/foldable-utils
  - location: ./packages/hlist
  - location: ./packages/position
extra-deps:
  #TODO: remove base-prelude extra-dep once it makes it back into Stackage. https://github.com/fpco/stackage/issues/3202 is part of it.
  - base-noprelude-4.10.1.0@rev:0
  #TODO: https://github.com/fpco/stackage/issues/3312; all the rest of these are fallout
  - transformers-compat-0.6.0.5@rev:0
  - bifunctors-5.5.2@rev:1
  - exceptions-0.9.0@rev:0
  - semigroupoids-5.2.2@rev:2
  - free-5@rev:1
  - lens-4.16@rev:0
  - kan-extensions-5.1@rev:1
  - adjunctions-4.4@rev:0
  - optparse-applicative-0.14.2.0@rev:0
