resolver: nightly-2018-07-11
packages:
  - location: ./packages/xml
  - location: ./packages/mappend
  - location: ./packages/twofinger
  - location: ./packages/prelude
  - location: ./packages/romnum
  - location: ./packages/foldable-utils
  - location: ./packages/hlist
  - location: ./packages/position
  - location: ./packages/d2cpack
extra-deps:
  #TODO: https://github.com/dhall-lang/dhall-to-cabal/issues/111
  - dhall-to-cabal-1.2.0.0@rev:0
  #TODO: remove base-prelude extra-dep once it makes it back into Stackage.
  - base-noprelude-4.11.1.0@rev:0
