resolver: nightly-2019-09-12
packages:
  - ./packages/xml-core
  - ./packages/xml-desc
  - ./packages/xhtml2html
  - ./packages/twofinger
  - ./packages/prelude
  - ./packages/romnum
  - ./packages/foldable-utils
  - ./packages/hlist
  - ./packages/position
  - ./packages/meta
  - ./packages/project-file
  - ./packages/defrost
  - ./packages/aeson-cabal
  - ./packages/dhondt
  - ./packages/freeze-plan
extra-deps:
  # TODO: https://github.com/commercialhaskell/stackage/issues/4761
  - Cabal-3.0.0.0@rev:0
  - cabal-plan-0.5.0.0@rev:1
  # TODO: https://github.com/commercialhaskell/stackage/issues/4804
  - lens-4.18@rev:0
