name: q4c12-refrigerate
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/refrigerate
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml
extra-doc-files:
  - "README.markdown"
extra-source-files:
  - "test/golden/*/out"
  - "test/golden/*/test.cabal"
  - "test/golden/*/*.freeze"

verbatim:
  cabal-version: "2.0"

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.9.1.0 && < 4.12"
  - &d-bytestring
    "bytestring >= 0.10.8.1 && < 0.11"
  - &d-Cabal
    "Cabal >= 1.24.2.0 && < 1.25 || >= 2.0.1.0 && < 2.1 || >= 2.2.0.1 && < 2.3"
  - &d-containers
    "containers >= 0.5.7.1 && < 0.6"
  - &d-dlist
    "dlist >= 0.8.0.4 && < 0.9"
  - &d-dlist-nonempty
    "dlist-nonempty >= 0.1.1 && < 0.2"
  - &d-lens
    "lens >= 4.17 && < 4.18"
  - &d-optparse-applicative
    "optparse-applicative >= 0.14.2.0 && < 0.15"
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.1"
  - &d-q4c12-project-file
    "q4c12-project-file >= 0 && < 0.1"
  - &d-tasty
    "tasty >= 1.1.0.2 && < 1.2"
  - &d-tasty-golden
    "tasty-golden >= 2.3.2 && < 2.4"
  - &d-text
    "text >= 1.2.3.0 && < 1.3"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Refrigerate
  other-modules: []
  dependencies:
    - *d-base
    - *d-bytestring
    - *d-Cabal
    - *d-containers
    - *d-dlist-nonempty
    - *d-lens
    - *d-q4c12-prelude
    - *d-q4c12-project-file
    - *d-text
  verbatim:
    mixins: "base hiding (Prelude)"

executables:
  refrigerate:
    main: driver/refrigerate.hs
    other-modules: []
    dependencies:
      - "q4c12-refrigerate"
      - *d-base
      - *d-bytestring
      - *d-Cabal
      - *d-optparse-applicative
      - *d-q4c12-prelude
      - *d-q4c12-project-file
      - *d-text
    verbatim:
      mixins: "base hiding (Prelude)"

tests:
  tasty:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      - "q4c12-refrigerate"
      - *d-base
      - *d-bytestring
      - *d-Cabal
      - *d-dlist
      - *d-q4c12-prelude
      - *d-q4c12-project-file
      - *d-tasty
      - *d-tasty-golden
      - *d-text
    verbatim:
      mixins: "base hiding (Prelude)"
