name: q4c12-refrigerate
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/refrigerate
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml
extra-doc-files:
  - "README.markdown"
extra-source-files:
  - "test/golden/*/out"
  - "test/golden/*/test.cabal"
  - "test/golden/*/*.freeze"

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Refrigerate
  other-modules: []
  dependencies:
    - base
    - bytestring
    - Cabal
    - containers
    - dlist-nonempty
    - lens
    - q4c12-prelude
    - q4c12-project-file
    - text
  verbatim:
    mixins: "base hiding (Prelude)"

executables:
  refrigerate:
    main: driver/refrigerate.hs
    other-modules: []
    dependencies:
      - q4c12-refrigerate
      - base
      - bytestring
      - Cabal
      - optparse-applicative
      - q4c12-prelude
      - q4c12-project-file
      - text
    verbatim:
      mixins: "base hiding (Prelude)"

tests:
  tasty:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      - q4c12-refrigerate
      - base
      - bytestring
      - Cabal
      - dlist
      - q4c12-prelude
      - q4c12-project-file
      - tasty
      - tasty-golden
      - text
    verbatim:
      mixins: "base hiding (Prelude)"
