spec-version: "0.31"
name: q4c12-defrost
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/defrost
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml
extra-doc-files:
  - "README.markdown"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Defrost
  other-modules: []
  dependencies:
    aeson:
    base:
      mixin:
        - hiding (Prelude)
    bytestring:
    Cabal:
    containers:
    dlist-nonempty:
    lens:
    process:
    q4c12-aeson-cabal:
    q4c12-prelude:
    q4c12-project-file:
    text:

tests:
  tasty:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      q4c12-defrost:
      base:
        mixin:
          - hiding (Prelude)
      bytestring:
      Cabal:
      containers:
      q4c12-prelude:
      q4c12-project-file:
      tasty:
      tasty-hunit:
      text:
