name: q4c12-defrost
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/defrost
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack-defaults.yaml
extra-doc-files:
  - "README.markdown"

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Defrost
  other-modules: []
  dependencies:
    - base
    - Cabal
    - containers
    - dlist-nonempty
    - lens
    - q4c12-prelude
    - q4c12-project-file
    - text
  verbatim:
    mixins: "base hiding (Prelude)"

tests:
  tasty:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      - q4c12-defrost
      - base
      - bytestring
      - Cabal
      - containers
      - lens
      - q4c12-prelude
      - q4c12-project-file
      - tasty
      - tasty-hunit
      - text
    verbatim:
      mixins: "base hiding (Prelude)"
