name: q4c12-meta
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/meta
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Meta
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "aeson >= 1.4.0.0 && < 1.5"
    - "base >= 4.10.1.0 && < 4.12"
    - "bytestring >= 0.10.8.2 && < 0.11"
    - "containers >= 0.5.10.2 && < 0.6"
    - "cryptohash-sha256 >= 0.11.101.0 && < 0.12"
    - "optparse-applicative >= 0.14.2.0 && < 0.15"
    - "q4c12-mappend >= 0 && < 0.1"
    - "q4c12-prelude >= 0 && < 0.1"
    - "q4c12-xml-core >= 0 && < 0.1"
    - "q4c12-xml-desc >= 0 && < 0.1"
    - "text >= 1.2.3.0 && < 1.3"
  verbatim:
    mixins: "base hiding (Prelude)"

executables:
  meta:
    main: driver/meta.hs
    other-modules: []
    dependencies:
      - "q4c12-meta"
