name: q4c12-meta
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/meta
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Meta
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - cryptohash-sha256
    - optparse-applicative
    - q4c12-mappend
    - q4c12-prelude
    - q4c12-xml-core
    - q4c12-xml-desc
    - text
  verbatim:
    mixins: "base hiding (Prelude)"

executables:
  meta:
    main: driver/meta.hs
    other-modules: []
    dependencies:
      - "q4c12-meta"
