spec-version: "0.31"
name: q4c12-meta
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/meta
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Meta
  # Suppress Paths_*
  other-modules: []
  dependencies:
    aeson:
    base:
      mixin:
        - hiding (Prelude)
    bytestring:
    Cabal:
    containers:
    cryptohash-sha256:
    optparse-applicative:
    process:
    q4c12-defrost:
    q4c12-mappend:
    q4c12-prelude:
    q4c12-project-file:
    q4c12-xml-core:
    q4c12-xml-desc:
    text:

executables:
  meta:
    main: driver/meta.hs
    other-modules: []
    dependencies:
      q4c12-meta:
