name: q4c12-xml
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/xml
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
extra-doc-files:
  - README.markdown
extra-source-files:
  - test/golden/**/*.in
  - test/golden/**/*.out
  - test/golden/**/*.errout
  - test/golden/**/*.fails
defaults:
  local: ../../hpack/defaults.rolling.yaml

_common-dependencies:
    # Define version ranges once and only once across components.
  - &d-base-noprelude
    "base-noprelude >= 4.9.1.0 && < 4.12"
  - &d-containers
    "containers >= 0.5.9.2 && < 0.7"
  - &d-criterion
    "criterion >= 1.5.0.0 && < 1.6"
  - &d-dlist
    "dlist >= 0.8.0.3 && < 0.9"
  - &d-dlist-nonempty
    "dlist-nonempty >= 0.1.1 && < 0.2"
  - &d-filepath
    "filepath >= 1.4.1.1 && < 1.5"
  - &d-formatting
    "formatting >= 6.3.0 && < 6.4"
  - &d-q4c12-mappend
    "q4c12-mappend >= 0 && < 0.1"
  - &d-q4c12-position
    "q4c12-position >= 0 && < 0.1"
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.0.1"
  - &d-q4c12-twofinger
    "q4c12-twofinger >= 0.2 && < 0.3"
  - &d-safe
    "safe >= 0.3.15 && < 0.4"
  - &d-tasty
    "tasty >= 0.12 && < 0.13 || >= 1.0 && < 1.2"
  - &d-tasty-expected-failure
    "tasty-expected-failure >= 0.11.0.4 && < 0.12"
  - &d-tasty-golden
    "tasty-golden >= 2.3.1.1 && < 2.4"
  - &d-template-haskell
    # No bounds, because you shouldn't be downloading template-haskell off hackage anyway, as opposed to using your GHC's one...
    "template-haskell"
  - &d-text
    "text >= 1.2.2.2 && < 1.3"
  - &d-text-icu
    "text-icu >= 0.7.0.1 && < 0.8"
  - &d-transformers
    "transformers >= 0.5 && < 0.6"
  - &d-transformers-compat
    "transformers-compat >= 0.6 && < 0.7"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.XML
    - Q4C12.XML.Desc
    - Q4C12.XML.Desc.Class
    - Q4C12.XML.Desc.Parse
    - Q4C12.XML.Desc.Print
    - Q4C12.XML.Desc.RApplicative
    - Q4C12.XML.Desc.RELAX
    - Q4C12.XML.Desc.TH
    - Q4C12.XML.Internal
    - Q4C12.XML.XHTML2HTML
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base-noprelude
    - *d-containers
    - *d-dlist
    - *d-dlist-nonempty
    - *d-formatting
    - *d-q4c12-twofinger
    - *d-q4c12-mappend
    - *d-q4c12-position
    - *d-q4c12-prelude
    - *d-safe
    - *d-template-haskell
    - *d-text
    - *d-text-icu
    - *d-transformers
    - *d-transformers-compat

executables:
  xhtml2html:
    main: driver/xhtml2html.hs
    # Suppress Paths_*
    other-modules: []
    dependencies:
      - q4c12-xml
      - *d-q4c12-prelude
      - *d-text

tests:
  golden-tests:
    main: test/Test.hs
    other-modules: []
    #TODO: clean up these warnings
    ghc-options:
      - "-Wno-monomorphism-restriction"
      - "-Wno-missing-local-signatures"
    dependencies:
      - q4c12-xml
      - *d-containers
      - *d-filepath
      - *d-q4c12-prelude
      - *d-tasty
      - *d-tasty-expected-failure
      - *d-tasty-golden
      - *d-text
      - *d-transformers

benchmarks:
  parse-xml:
    main: bench/parse-xml.hs
    other-modules: []
    dependencies:
      - q4c12-xml
      - *d-criterion
      - *d-q4c12-prelude
      - *d-text

#TODO: property-based testing. Round-trip render/parse.
