name: q4c12-hlist
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/hlist
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.HList
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - lens
