name: q4c12-xml-desc
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/xml-desc
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
extra-doc-files:
  - README.markdown
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

_common-dependencies:
    # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.10.1.0 && < 4.12"
  - &d-containers
    "containers >= 0.5.9.2 && < 0.7"
  - &d-criterion
    "criterion >= 1.5.0.0 && < 1.6"
  - &d-dlist
    "dlist >= 0.8.0.3 && < 0.9"
  - &d-dlist-nonempty
    "dlist-nonempty >= 0.1.1 && < 0.2"
  - &d-filepath
    "filepath >= 1.4.1.1 && < 1.5"
  - &d-q4c12-mappend
    "q4c12-mappend >= 0 && < 0.1"
  - &d-q4c12-position
    "q4c12-position >= 0 && < 0.1"
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.0.1"
  - &d-q4c12-twofinger
    "q4c12-twofinger >= 0.2 && < 0.3"
  - &d-q4c12-xml-core
    "q4c12-xml-core >= 0 && < 0.1"
  - &d-safe
    "safe >= 0.3.15 && < 0.4"
  - &d-template-haskell
    # No bounds, because you shouldn't be downloading template-haskell off hackage anyway, as opposed to using your GHC's one...
    "template-haskell"
  - &d-text
    "text >= 1.2.2.2 && < 1.3"
  - &d-text-icu
    "text-icu >= 0.7.0.1 && < 0.8"
  - &d-transformers
    "transformers >= 0.5 && < 0.6"
  - &d-transformers-compat
    "transformers-compat >= 0.6 && < 0.7"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.XMLDesc
    - Q4C12.XMLDesc.Class
    - Q4C12.XMLDesc.Parse
    - Q4C12.XMLDesc.Print
    - Q4C12.XMLDesc.RApplicative
    - Q4C12.XMLDesc.RELAX
    - Q4C12.XMLDesc.TH
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base
    - *d-containers
    - *d-dlist
    - *d-dlist-nonempty
    - *d-q4c12-twofinger
    - *d-q4c12-mappend
    - *d-q4c12-position
    - *d-q4c12-prelude
    - *d-q4c12-xml-core
    - *d-safe
    - *d-template-haskell
    - *d-text
    - *d-text-icu
    - *d-transformers
    - *d-transformers-compat
  verbatim:
    mixins: "base hiding (Prelude)"

#TODO: tests
