spec-version: "0.31"
name: q4c12-xml-desc
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/xml-desc
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
extra-doc-files:
  - README.markdown
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.XMLDesc
    - Q4C12.XMLDesc.Class
    - Q4C12.XMLDesc.Parse
    - Q4C12.XMLDesc.Print
    - Q4C12.XMLDesc.RApplicative
    - Q4C12.XMLDesc.RELAX
    - Q4C12.XMLDesc.TH
  # Suppress Paths_*
  other-modules: []
  dependencies:
    base:
      mixin:
        - hiding (Prelude)
    containers:
    dlist:
    dlist-nonempty:
    q4c12-twofinger:
    q4c12-mappend:
    q4c12-position:
    q4c12-prelude:
    q4c12-xml-core:
    safe:
    template-haskell:
    text:
    text-icu:
    transformers:
      # Hide the leaky WriterT
      mixin:
        - hiding (Control.Monad.Trans.RWS, Control.Monad.Trans.Writer)
    transformers-compat:
    writer-cps-transformers:

#TODO: tests
