name: q4c12-mappend
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/mappend
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

#TODO: replace with hpack's defaulting mechanism, once that has support for local files
<<: !include "../../defaults.yaml"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.MapPend
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "base >= 4.8.2.0 && < 4.11"
    - "containers >= 0.5.7.1 && < 0.6"
    - "lens >= 4.15.4 && < 4.16"
