name: q4c12-project-file
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/project-file
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack-defaults.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.ProjectFile
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - Cabal
    - containers
    - megaparsec
    - parser-combinators
    - q4c12-prelude
    - text
  verbatim:
    mixins: "base hiding (Prelude)"

tests:
  unit-tests:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      - q4c12-project-file
      - base
      - Cabal
      - containers
      - q4c12-prelude
      - tasty
      - tasty-hunit
      - text
    verbatim:
      mixins: "base hiding (Prelude)"
