name: q4c12-project-file
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/project-file
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.9.1.0 && < 4.12"
  - &d-Cabal
    "Cabal >= 2.2.0.1 && < 2.3"
  - &d-containers
    "containers >= 0.5.7.1 && < 0.6"
  - &d-megaparsec
    "megaparsec >= 6.5.0 && < 6.6"
  - &d-parser-combinators
    "parser-combinators >= 1.0.0 && < 1.1"
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.0.1"
  - &d-tasty
    "tasty >= 1.0 && < 1.2"
  - &d-tasty-hunit
    "tasty-hunit >= 0.10 && < 0.11"
  - &d-text
    "text >= 1.2.3.0 && < 1.3"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.ProjectFile
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base
    - *d-Cabal
    - *d-containers
    - *d-megaparsec
    - *d-parser-combinators
    - *d-q4c12-prelude
    - *d-text
  verbatim:
    mixins: "base hiding (Prelude)"

tests:
  unit-tests:
    main: test/tasty.hs
    other-modules: []
    dependencies:
      - "q4c12-project-file"
      - *d-base
      - *d-Cabal
      - *d-containers
      - *d-q4c12-prelude
      - *d-tasty
      - *d-tasty-hunit
      - *d-text
    verbatim:
      mixins: "base hiding (Prelude)"
