name: q4c12-refreeze
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/refreeze
github: quasicomputational/refreeze
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Refreeze
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - process
    - q4c12-prelude
    - q4c12-xml-core
    - q4c12-xml-desc
    - text
  verbatim:
    mixins: "base hiding (Prelude)"

executables:
  refreeze:
    main: driver/refreeze.hs
    other-modules: []
    dependencies:
      - q4c12-refreeze
