name: q4c12-prelude
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/optic
github: quasicomputational/prelude
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

ghc-options: !include "../../ghc-options.yaml"
default-extensions: !include "../../language.yaml"

library:
  source-dirs:
    - src
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "base-noprelude >= 4.9.1.0 && < 4.11"
    - "bifunctors >= 5.5 && < 5.6"
    - "containers >= 0.5.9.2 && < 0.6"
    - "deepseq >= 1.4.3.0 && < 1.5"
    - "dlist >= 0.8.0.3 && < 0.9"
    - "dlist-nonempty >= 0.1.1 && < 0.2"
    - "either >= 5 && < 5.1"
    - "filepath >= 1.4.1.1 && < 1.5"
    - "lens >= 4.15.4 && < 4.16"
    - "profunctors >= 5.2.1 && < 5.3"
    - "q4c12-foldable-utils >= 0 && < 0.1"
    - "q4c12-hlist >= 0 && < 0.1"
    #TODO: replace with real transformers-compat
    - "q4c12-transformers-compat >= 0 && < 0.1"
    - "q4c12-twofinger >= 0.2 && < 0.3"
    - "semigroupoids >= 5.2.1 && < 5.3"
    - "text >= 1.2.2.2 && < 1.3"
    - "transformers >= 0.5 && < 0.6"
