name: q4c12-prelude
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/optic
github: quasicomputational/prelude
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Prelude
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base-noprelude
    - bifunctors
    - containers
    - deepseq
    - dlist
    - dlist-nonempty
    - either
    - filepath
    - lens
    - profunctors
    - q4c12-foldable-utils
    - q4c12-hlist
    - q4c12-twofinger
    - semigroupoids
    - text
    - transformers
    - transformers-compat
