spec-version: "0.31"
name: q4c12-prelude
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/optic
github: quasicomputational/prelude
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
extra-doc-files:
  - README.markdown
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Prelude
  # Suppress Paths_*
  other-modules: []
  dependencies:
    base:
      mixin:
        - hiding (Prelude)
    bifunctors:
    bytestring:
    containers:
    deepseq:
    directory:
    dlist:
    dlist-nonempty:
    either:
    filepath:
    invariant:
    kan-extensions:
    lens:
    monoidal-containers:
    profunctors:
    q4c12-foldable-utils:
    q4c12-hlist:
    q4c12-twofinger:
    semigroupoids:
    template-haskell:
    temporary:
    text:
    time:
    time-compat:
    transformers:
      mixin:
        # Hide the leaky writer versions
        - hiding (Control.Monad.Trans.RWS, Control.Monad.Trans.Writer)
    witherable:
    writer-cps-transformers:
  when:
    condition: "!impl(ghc >= 8.6)"
    dependencies:
      contravariant:
