name: q4c12-xhtml2html
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/xhtml2html
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
extra-doc-files:
  - README.markdown
extra-source-files:
  - test/golden/**/*.in
  - test/golden/**/*.out
  - test/golden/**/*.fails
defaults:
  local: ../../hpack/defaults.rolling.yaml

library:
  source-dirs:
    src
  exposed-modules:
    - Q4C12.XHTML2HTML
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - containers
    - q4c12-position
    - q4c12-prelude
    - q4c12-twofinger
    - q4c12-xml-core
    - text

executables:
  xhtml2html:
    main: driver/xhtml2html.hs
    # Suppress Paths_*
    other-modules: []
    dependencies:
      - q4c12-xhtml2html
      - q4c12-prelude
      - q4c12-xml-core
      - text

tests:
  golden-tests:
    main: test/Test.hs
    other-modules: []
    #TODO: clean up these warnings
    ghc-options:
      - "-Wno-monomorphism-restriction"
      - "-Wno-missing-local-signatures"
    dependencies:
      - q4c12-xhtml2html
      - filepath
      - q4c12-prelude
      - q4c12-xml-core
      - tasty
      - tasty-golden
      - text
      - transformers

#TODO: property-based testing. Round-trip render/parse.
