name: q4c12-romnum
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/romnum
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

#TODO: replace with hpack's defaulting mechanism, once that has support for local files
<<: !include "../../defaults.yaml"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.RomNum
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "q4c12-prelude >= 0 && < 0.0.1"

#TODO: write/port over some tests
