spec-version: "0.31"
name: q4c12-romnum
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/romnum
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.RomNum
  # Suppress Paths_*
  other-modules: []
  dependencies:
    q4c12-prelude:

tests:
  unit-tests:
    main: test/UnitTests.hs
    other-modules: []
    dependencies:
      q4c12-romnum:
      q4c12-prelude:
      tasty:
      tasty-hunit:
      text:
