name: q4c12-romnum
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/romnum
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-q4c12-prelude
    "q4c12-prelude >= 0 && < 0.0.1"
  - &d-tasty
    "tasty >= 1.0 && < 1.1"
  - &d-tasty-hunit
    "tasty-hunit >= 0.10 && < 0.11"
  - &d-text
    "text >= 1.2.3.0 && < 1.3"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.RomNum
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-q4c12-prelude

tests:
  unit-tests:
    source-dirs:
      - test
    main:
      UnitTests.hs
    other-modules: []
    dependencies:
      - "q4c12-romnum"
      - *d-q4c12-prelude
      - *d-tasty
      - *d-tasty-hunit
      - *d-text
