name: q4c12-foldable-utils
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/foldable-utils
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    - "Cabal"
    - base
    - cabal-doctest

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.FoldableUtils
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - transformers
  when:
    #TODO: rm once 8.0 is unsupported
    - condition: impl(ghc < 8.2)
      dependencies:
        - bifunctors
    - condition: "true"
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      ghc-options:
        #Post-SMP, our signatures strictly are redundant. However, for implementation sanity, they need to be that way on 8.2. TODO: remove this once 8.2 is out of the window.
        - "-Wno-redundant-constraints"

tests:
  doctests:
    source-dirs:
      - test
    main: Doctest.hs
    #Suppress Paths_*
    other-modules: []
    when:
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      - condition: "true"
        ghc-options:
          #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
          - "-Wno-missing-import-lists"
      - condition: impl(ghc >= 8.4)
        ghc-options:
          #TODO: file a but about this, too
          - "-Wno-missing-export-lists"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      - q4c12-foldable-utils
      - base
      - doctest
