name: q4c12-foldable-utils
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/foldable-utils
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

#TODO: replace with hpack's defaulting mechanism, once that has support for local files
<<: !include "../../defaults.yaml"

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.9.1.0 && < 4.11"
  - &d-bifunctors
    "bifunctors >= 5.4.2 && < 5.5"
  - &d-cabal-doctest
    "cabal-doctest >= 1.0.5 && < 1.1"
  - &d-doctest
    "doctest >= 0.11.4 && < 0.14"
  - &d-transformers
    "transformers >= 0.5 && < 0.6"

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    - "Cabal"
    - *d-base
    - *d-cabal-doctest

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.FoldableUtils
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base
    - *d-transformers
  when:
    #TODO: rm once 8.0 is unsupported
    - condition: impl(ghc < 8.2)
      dependencies:
        - *d-bifunctors

tests:
  doctests:
    source-dirs:
      - test
    main: Doctest.hs
    #Suppress Paths_*
    other-modules: []
    when:
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      condition: "true"
      ghc-options:
        #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
        - "-Wno-missing-import-lists"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      - q4c12-foldable-utils
      - *d-base
      - *d-doctest
