spec-version: "0.31"
name: q4c12-foldable-utils
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/foldable-utils
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    Cabal:
    base:
    cabal-doctest:

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.FoldableUtils
  # Suppress Paths_*
  other-modules: []
  dependencies:
    base:
    lens:
    transformers:
      mixin:
        # Hide the leaky writer versions
        - hiding (Control.Monad.Trans.RWS, Control.Monad.Trans.Writer)

tests:
  doctests:
    main: test/Doctest.hs
    #Suppress Paths_*
    other-modules: []
    when:
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      - condition: "true"
        ghc-options:
          #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
          - "-Wno-missing-import-lists"
          #TODO: file a bug about this, too
          - "-Wno-missing-export-lists"
      - condition: "impl(ghc >= 8.8)"
        ghc-options:
          - "-Wno-missing-deriving-strategies"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      q4c12-foldable-utils:
      base:
      doctest:
