name: q4c12-position
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/position
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Position
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "base >= 4.9.1.0 && < 4.12"
    - "q4c12-prelude >= 0 && < 0.0.1"
    - "text >= 1.2.2.2 && < 1.3"
  verbatim:
    mixins: "base hiding (Prelude)"
