name: q4c12-position
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/position
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
defaults:
  local: ../../hpack/defaults.rolling.yaml

verbatim:
  cabal-version: "2.0"

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Position
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - q4c12-prelude
    - text
  verbatim:
    mixins: "base hiding (Prelude)"
