spec-version: "0.31"
name: q4c12-position
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/position
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.Position
  # Suppress Paths_*
  other-modules: []
  dependencies:
    base:
      mixin:
        - hiding (Prelude)
    q4c12-prelude:
    text:
