name: q4c12-transformers-compat
version: "0"
license: BSD3
license-file:
  - LICENSE
copyright: Copyright (C) 2012-2015 Edward A. Kmett

flags:
  five-dot-two:
    manual: False
    default: True
  five-dot-three:
    manual: False
    default: False

library:
  source-dirs:
    - src
  exposed-modules: []
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base >= 4.9.1.0 && < 4.11
  when:
    - condition: flag(five-dot-two)
      dependencies:
        - transformers >= 0.5 && < 0.5.3
      exposed-modules:
        - Control.Monad.Trans.Accum
    - condition: flag(five-dot-three)
      dependencies:
        - transformers >= 0.5.3 && < 0.6
      reexported-modules:
        - Control.Monad.Trans.Accum
