name: q4c12-optic
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/optic
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

ghc-options: !include "../../ghc-options.yaml"
default-extensions: !include "../../language.yaml"

library:
  source-dirs:
    - src
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "base >= 4.9.1.0 && < 4.11"
    - "profunctors >= 5.2.1 && < 5.3"
