name: q4c12-twofinger
version: "0.2.0.1"
synopsis: Efficient alternating finger trees
description: |
  This package provides efficient alternating sequences based on finger trees. These can represent sequences made up of two types of element, @e@ and @a@  where two of the same type of element cannot follow each other directly.
  .
  Four different flavours are provided, isomorphic to @([(a, e)], a)@, @([(e, a)], e)@, @[(a, e)]@, and @[(e, a)]@.
  .
  Cons-like operations are /O(1)/ amortised, and append operations are /O(log(min(n, m)))/ amortised.
  .
  For more details, please see the Haddock documentation of "Q4C12.TwoFinger".
homepage: https://github.com/quasicomputational/mega/tree/master/packages/twofinger
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
maintainer: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
category: Data Structures
extra-doc-files:
  - README.markdown
  - CHANGELOG.markdown
  #TODO: Should this file (i.e., package.yaml) be included in sdists? Question of what to do for the includes, in that case.
defaults:
  local: ../../hpack-defaults.yaml

#TODO: https://github.com/commercialhaskell/stack/issues/2583 means we can't get away with putting the QuickCheck stuff into another package.

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    - Cabal
    - base
    - cabal-doctest

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.TwoFinger
    - Q4C12.TwoFinger.Internal
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - containers
    - deepseq
    - semigroupoids
  when:
    - condition: "true"
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      ghc-options:
        #Post-SMP, our signatures strictly are redundant. However, for implementation sanity, they need to be that way on 8.2. TODO: remove this once 8.2 is out of the window.
        - "-Wno-redundant-constraints"

#TODO: cabal-doctest (or perhaps doctest itself) doesn't play nicely with coverage reports.
tests:
  properties:
    main: test/Properties.hs
    other-modules: []
    dependencies:
      - q4c12-twofinger
      - base
      - lens
      - lens-properties
      - QuickCheck
      - tasty
      - tasty-quickcheck
  doctests:
    main: test/Doctest.hs
    other-modules: []
    when:
      #Have to specify this in a conditional because of https://github.com/sol/hpack/issues/255 TODO remove once fixed
      - condition: "true"
        ghc-options:
          #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
          - "-Wno-missing-import-lists"
      - condition: impl(ghc >= 8.4)
        ghc-options:
          #TODO: file a but about this, too
          - "-Wno-missing-export-lists"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      - q4c12-twofinger
      - base
      - doctest
      - lens

#TODO: Benchmarks!
