name: q4c12-twofinger
version: "0.2.0.1"
synopsis: Efficient alternating finger trees
description: |
  This package provides efficient alternating sequences based on finger trees. These can represent sequences made up of two types of element, @e@ and @a@  where two of the same type of element cannot follow each other directly.
  .
  Four different flavours are provided, isomorphic to @([(a, e)], a)@, @([(e, a)], e)@, @[(a, e)]@, and @[(e, a)]@.
  .
  Cons-like operations are /O(1)/ amortised, and append operations are /O(log(min(n, m)))/ amortised.
  .
  For more details, please see the Haddock documentation of "Q4C12.TwoFinger".
homepage: https://github.com/quasicomputational/mega/tree/master/packages/twofinger
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
maintainer: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
category: Data Structures
extra-doc-files:
  - README.markdown
  - CHANGELOG.markdown
  #TODO: Should this file (i.e., package.yaml) be included in sdists? Question of what to do for the includes, in that case.

ghc-options: !include "../../ghc-options.yaml"
default-extensions: !include "../../language.yaml"

#TODO: https://github.com/commercialhaskell/stack/issues/2583 means we can't get away with putting the QuickCheck stuff into another package.

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.9.1.0 && < 4.11"
  - &d-bifunctors
    "bifunctors >= 5.4.2 && < 5.6"
  - &d-cabal-doctest
    "cabal-doctest >= 1.0.3 && < 1.1"
  - &d-containers
    "containers >= 0.5.10.2 && < 0.5.11"
  - &d-deepseq
    "deepseq >= 1.4.3.0 && < 1.5"
  - &d-doctest
    "doctest >= 0.11.4 && < 0.14"
  - &d-lens
    "lens >= 4.15.4 && < 4.16"
  - &d-lens-properties
    "lens-properties >= 4.11.1 && < 4.12"
  - &d-semigroupoids
    "semigroupoids >= 5.2.1 && < 5.3"
  - &d-tasty
    "tasty >= 0.12 && < 0.13 || >= 1.0 && < 1.1"
  - &d-tasty-quickcheck
    "tasty-quickcheck >= 0.9.1 && < 0.10"

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    - "Cabal"
    - *d-base
    - *d-cabal-doctest

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.TwoFinger
    - Q4C12.TwoFinger.Internal
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base
    - *d-containers
    - *d-deepseq
    - *d-semigroupoids
  when:
    - condition: impl(ghc < 8.2)
      dependencies:
        - *d-bifunctors

#TODO: cabal-doctest (or perhaps doctest itself) doesn't play nicely with coverage reports.
tests:
  properties:
    source-dirs:
      - test
    main: Properties.hs
    other-modules: []
    dependencies:
      - q4c12-twofinger
      - *d-base
      - *d-lens
      - *d-lens-properties
      - *d-tasty
      - *d-tasty-quickcheck
  doctests:
    source-dirs:
      - test
    main: Doctest.hs
    other-modules: []
    #TODO: Build_doctests ought to be listed as an autogen-module and an other-module, but hpack doesn't know about autogen modules: https://github.com/sol/hpack/issues/207
    ghc-options:
      #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
      - "-Wno-missing-import-lists"
      #And this one is as a result of the Build_doctests hack above
      - "-Wno-missing-home-modules"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      - q4c12-twofinger
      - *d-base
      - *d-doctest
      - *d-lens

#TODO: Benchmarks!
