name: q4c12-twofinger
version: "0"
synopsis: Efficient alternating finger trees
homepage: https://github.com/quasicomputational/mega/tree/master/packages/twofinger
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
maintainer: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2
category: Data Structures
extra-source-files:
  #TODO: should be under extra-doc-files
  - README.markdown
  #TODO: Should this file (i.e., package.yaml) be included in sdists? Question of what to do for the includes, in that case.

ghc-options: !include "../../ghc-options.yaml"
default-extensions: !include "../../language.yaml"

#TODO: https://github.com/commercialhaskell/stack/issues/2583 means we can't get away with putting the QuickCheck stuff into another package.

_common-dependencies:
  # Define version ranges once and only once across components.
  - &d-base
    "base >= 4.9.1.0 && < 4.11"
  - &d-bifunctors
    "bifunctors >= 5.4.2 && < 5.5"
  - &d-cabal-doctest
    "cabal-doctest >= 1.0.3 && < 1.1"
  - &d-deepseq
    "deepseq >= 1.4.3.0 && < 1.5"
  - &d-doctest
    "doctest >= 0.11.4 && < 0.14"
  - &d-lens
    "lens >= 4.15.4 && < 4.16"
  - &d-QuickCheck
    "QuickCheck >= 2.10.1 && < 2.11"
  - &d-semigroupoids
    "semigroupoids >= 5.2.1 && < 5.3"
  #TODO: we only use streams minimally, but it's got a pretty heavy dependency load. On the other hand, the dependencies are there to define instances.
  - &d-streams
    "streams >= 3.3 && < 3.4"

custom-setup:
  dependencies:
    #TODO: remove Cabal dep once https://github.com/haskell/cabal/issues/4288 is fixed
    - "Cabal"
    - *d-base
    - *d-cabal-doctest

library:
  source-dirs:
    - src
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - *d-base
    - *d-deepseq
    - *d-QuickCheck
    - *d-semigroupoids
    - *d-streams
  when:
    - condition: impl(ghc < 8.2)
      dependencies:
        - *d-bifunctors

#TODO: cabal-doctest (or perhaps doctest itself) doesn't play nicely with coverage reports.
tests:
  doctests:
    source-dirs:
      - test
    main: Doctest.hs
    #TODO: Build_doctests ought to be listed as an autogen-module and an other-module, but hpack doesn't know about autogen modules: https://github.com/sol/hpack/issues/207
    ghc-options:
      #TODO: this is needed because cabal-doctest generates a module that triggers this warning. Sigh. Should file a bug about that...
      - "-Wno-missing-import-lists"
      #And this one is as a result of the Build_doctests hack above
      - "-Wno-missing-home-modules"
    dependencies:
      #https://github.com/phadej/cabal-doctest/issues/19
      - q4c12-twofinger
      - *d-base
      - *d-doctest
      - *d-lens
      - *d-streams
      #cabal-doctest related hacks
      - *d-QuickCheck
      - "template-haskell"

#TODO: Benchmarks!
