name: q4c12-validate
version: "0"
author: quasicomputational <quasicomputational@gmail.com>
license: BSD2
license-file:
  - LICENSE.BSD2

ghc-options: !include "../../ghc-options.yaml"
default-extensions: !include "../../language.yaml"

library:
  source-dirs:
    - src
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - "base >= 4.9.1.0 && < 4.11"
    - "semigroupoids >= 5.2.1 && < 5.3"
    - "transformers >= 0.5.5.0 && < 0.6"

#TODO: get rid of this package and depend on ekmett/either; don't want to do this until that package has shed some deps though (which will happen at some point!)
