name: q4c12-xml-core
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/xml-core
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
extra-doc-files:
  - README.markdown
extra-source-files:
  - test/golden/**/*.in
  - test/golden/**/*.out
  - test/golden/**/*.errout
  - test/golden/**/*.fails
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.XML
    - Q4C12.XML.Internal
    - Q4C12.XML.QQ
  # Suppress Paths_*
  other-modules: []
  dependencies:
    - base
    - containers
    - dlist
    - dlist-nonempty
    - q4c12-twofinger
    - q4c12-mappend
    - q4c12-position
    - q4c12-prelude
    - safe
    - template-haskell
    - text
    - text-icu
    - transformers
    - transformers-compat
    - writer-cps-transformers
  verbatim:
    mixins: |
      base hiding (Prelude),
      -- Hide the leaky transformers
      transformers hiding (Control.Monad.Trans.RWS, Control.Monad.Trans.Writer)

tests:
  golden-tests:
    main: test/Test.hs
    other-modules: []
    #TODO: clean up these warnings
    ghc-options:
      - "-Wno-monomorphism-restriction"
      - "-Wno-missing-local-signatures"
    dependencies:
      - q4c12-xml-core
      - containers
      - filepath
      - q4c12-prelude
      - tasty
      - tasty-expected-failure
      - tasty-golden
      - text
      - transformers

benchmarks:
  parse-xml:
    main: bench/parse-xml.hs
    other-modules: []
    dependencies:
      - q4c12-xml-core
      - criterion
      - q4c12-prelude
      - text

#TODO: property-based testing. Round-trip render/parse.
