spec-version: "0.31"
name: q4c12-freeze-plan
version: "0"
homepage: https://github.com/quasicomputational/mega/tree/master/packages/freeze-plan
github: quasicomputational/mega
author: quasicomputational <quasicomputational@gmail.com>
license: Apache-2.0 OR LGPL-2.1-or-later
license-file:
  - LICENSE.APACHE-2.0
  - LICENSE.LGPL-2.1
defaults:
  local: ../../hpack-defaults.yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Q4C12.FreezePlan
  # Suppress Paths_*
  other-modules: []
  dependencies:
    base:
      mixin:
        - hiding (Prelude)
    Cabal:
    cabal-plan:
    # TODO: we're depending on an internal API, so we should keep a tight bound.
    containers:
    q4c12-compose-key:
    q4c12-prelude:
    q4c12-project-file:
    text:
    transformers:
      mixin:
        # Hide the leaky writer versions
        - hiding (Control.Monad.Trans.RWS, Control.Monad.Trans.Writer)
    writer-cps-transformers:
